import React from "react";
import { Landmark, Scroll, BookOpen, Feather, Hourglass } from "lucide-react";

/* Title Slide – Split diagonal gold panel */
export function TitleSlide({ title, subtitle }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-yellow-900 text-yellow-100 overflow-hidden flex items-center justify-center">
      {/* Diagonal golden panel */}
      <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-br from-yellow-600 to-yellow-400 transform -skew-y-6 origin-top-left"></div>

      {/* Text */}
      <div className="relative z-10 text-center">
        <h1 className="text-6xl font-serif font-bold drop-shadow mb-4">{title}</h1>
        <h2 className="text-2xl italic font-serif">{subtitle}</h2>
      </div>
    </section>
  );
}


export function TOCSlide({ tocData }) {
  // Handle both old format (items array) and new format (tocData object)
  const title = tocData?.title || "Table of Contents";
  const sections = tocData?.sections || [];
  
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#fdfaf3] text-[#2b2b2b] flex flex-col items-center justify-center overflow-hidden">
      {/* Parchment texture overlay */}
      <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/aged-paper.png')] opacity-50"></div>

      {/* Ornamental border */}
      <div className="absolute inset-16 border-[8px] border-[#8b5e3c] rounded-xl shadow-lg"></div>

      {/* Classical icons */}
      <div className="absolute top-24 left-24 text-7xl text-[#8b5e3c]/40">🏛️</div>
      <div className="absolute bottom-24 right-24 text-7xl text-[#b08d57]/40">📜</div>

      {/* Title */}
      <h2 className="text-6xl font-serif font-bold text-[#5a3d2b] mb-16 drop-shadow-lg">
        {title}
      </h2>

      {/* Two-Column Layout for TOC - Minimized to show only main sections */}
      <div className="grid grid-cols-2 gap-20 z-10 max-w-6xl w-full">
        {/* Left Column */}
        <div className="space-y-10">
          {sections.slice(0, Math.ceil(sections.length / 2)).map((section, sectionIndex) => (
            <div key={sectionIndex} className="flex items-center gap-8 hover:text-[#8b5e3c] transition-colors duration-300 group">
              <span className="w-20 h-20 flex items-center justify-center rounded-full bg-gradient-to-br from-[#d4af37] to-[#a67c00] group-hover:from-[#e6c547] group-hover:to-[#b8860b] text-white font-bold text-2xl shadow-lg border-3 border-amber-200 group-hover:border-amber-300 flex-shrink-0 transition-all duration-300">
                {sectionIndex + 1}
              </span>
              <span className="text-5xl font-bold text-left leading-tight flex-1 group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
            </div>
          ))}
        </div>

        {/* Right Column */}
        <div className="space-y-10">
          {sections.slice(Math.ceil(sections.length / 2)).map((section, sectionIndex) => {
            const actualIndex = Math.ceil(sections.length / 2) + sectionIndex;
            return (
              <div key={actualIndex} className="flex items-center gap-8 hover:text-[#8b5e3c] transition-colors duration-300 group">
                <span className="w-20 h-20 flex items-center justify-center rounded-full bg-gradient-to-br from-[#d4af37] to-[#a67c00] group-hover:from-[#e6c547] group-hover:to-[#b8860b] text-white font-bold text-2xl shadow-lg border-3 border-amber-200 group-hover:border-amber-300 flex-shrink-0 transition-all duration-300">
                  {actualIndex + 1}
                </span>
                <span className="text-5xl font-bold text-left leading-tight flex-1 group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

/* ---------------- MAIN SLIDE 1 ---------------- */
export function MainSlide1({ title, content, imageUrl, autoGeneratedImage }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-[#f5f1e8] to-[#e8dcc6] text-[#5a3d2b] flex items-center justify-between px-16 overflow-hidden">
      {/* Decorative elements */}
      <div className="absolute top-20 left-20 w-40 h-40 rounded-full bg-gradient-to-br from-[#d4af37]/30 to-[#a67c00]/30 blur-2xl"></div>
      <div className="absolute bottom-20 right-20 w-56 h-56 rounded-full bg-gradient-to-br from-[#b08d57]/30 to-[#8b5e3c]/30 blur-2xl"></div>

      {/* Left side: Auto-generated image placeholder for 2nd term */}
      <div className="relative z-10 w-1/2 h-full flex items-center justify-center pr-12">
        {autoGeneratedImage ? (
          <img 
            src={autoGeneratedImage} 
            alt={title} 
            className="max-w-full max-h-full object-contain rounded-lg shadow-2xl border-8 border-[#d4af37]" 
          />
        ) : (
          <div className="w-4/5 h-4/5 bg-[#f9f6f0]/90 backdrop-blur-sm border-8 border-[#d4af37] rounded-2xl flex flex-col items-center justify-center shadow-2xl">
            <div className="text-[#5a3d2b] text-3xl font-serif font-bold mb-4">🎨 Auto Image Placeholder</div>
            <span className="text-[#8b5e3c] text-xl text-center px-4 font-serif">2nd Term: {title}</span>
          </div>
        )}
      </div>

      {/* Right side: Term and definition */}
      <div className="relative z-10 w-1/2 pl-12">
        <div className="bg-[#f9f6f0]/90 backdrop-blur-sm border-4 border-[#d4af37] rounded-2xl p-8 shadow-2xl">
          <h2 className="text-6xl font-serif font-bold mb-6 text-[#5a3d2b]">{title}</h2>
          <div className="h-[4px] w-48 bg-gradient-to-r from-[#d4af37] to-[#a67c00] mb-6"></div>
          {content && (
            <div className="bg-gradient-to-br from-yellow-50/80 to-yellow-100/80 border-l-4 border-[#d4af37] p-6 rounded-r-lg">
              <p className="text-4xl leading-relaxed text-[#8b5e3c] font-serif">{content}</p>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}

// Keep old component for backward compatibility
export function TOCSlideHistoryHeritage({ title = "Table of Contents", items = [] }) {
  const tocData = {
    title,
    sections: items.map(item => ({ title: item, subsections: [] }))
  };
  return <TOCSlide tocData={tocData} />;
}

const HistoryHeritage = {
  TitleSlide,
  TOCSlide,
  MainSlide1,
  MainSlide2,
  MainSlide3,
  EndSlide,
};

export default HistoryHeritage;

/* Main Slide 2 – Framed parchment with top banner */
export function MainSlide2({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-tr from-yellow-200 to-yellow-50 text-gray-900 p-16">
      {/* Ornamental frame */}
      <div className="absolute inset-6 border-[8px] border-yellow-700 rounded-lg"></div>

      {/* Title banner */}
      <div className="relative bg-gradient-to-r from-yellow-800 to-yellow-600 px-12 py-4 mb-10 shadow-lg w-fit">
        <h2 className="text-6xl font-serif font-bold text-yellow-100">{title}</h2>
      </div>

      <p className="text-3xl font-serif max-w-5xl leading-relaxed relative z-10">{content}</p>
    </section>
  );
}

/* Main Slide 3 – Diagonal cut layout with golden overlay */
export function MainSlide3({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] flex text-yellow-100">
      {/* Background */}
      <div className="absolute inset-0 bg-gradient-to-br from-yellow-900 via-yellow-800 to-yellow-600"></div>

      {/* Diagonal gold overlay */}
      <div className="absolute top-0 right-0 w-2/3 h-full bg-gradient-to-bl from-yellow-700/80 to-yellow-500/70 transform -skew-x-6 origin-top-right"></div>

      {/* Layout */}
      <div className="relative z-10 flex w-full h-full">
        {/* Title sidebar */}
        <div className="w-1/3 flex items-center justify-center bg-yellow-900/40">
          <h2 className="text-5xl font-serif font-bold text-yellow-100 text-center px-6">
            {title}
          </h2>
        </div>

        {/* Content area */}
        <div className="flex-1 flex items-center p-16">
          <p className="text-3xl font-serif leading-relaxed">{content}</p>
        </div>
      </div>
    </section>
  );
}

/* Main Slide 4 – Scroll layout (ancient scroll effect) */
export function MainSlide4({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-b from-yellow-200 to-yellow-50 flex flex-col items-center justify-center text-gray-900 overflow-hidden">

      {/* Subtle background icons */}
      <Landmark className="absolute top-20 left-28 w-32 h-32 text-yellow-600 opacity-25 rotate-6" />
      <Scroll className="absolute bottom-24 right-32 w-28 h-28 text-amber-500 opacity-25 rotate-[-8deg]" />
      <BookOpen className="absolute top-1/3 right-1/4 w-28 h-28 text-orange-400 opacity-25" />
      <Feather className="absolute bottom-1/3 left-1/4 w-24 h-24 text-red-400 opacity-25" />
      <Hourglass className="absolute top-1/2 right-16 w-28 h-28 text-emerald-500 opacity-25 rotate-3" />

      {/* Decorative border */}
      <div className="absolute inset-12 border-4 border-amber-600 rounded-lg opacity-30" />

      {/* Scroll edges */}
      <div className="absolute top-0 left-0 w-full h-20 bg-yellow-700 rounded-b-full"></div>
      <div className="absolute bottom-0 left-0 w-full h-20 bg-yellow-700 rounded-t-full"></div>

      {/* Content Wrapper */}
      <div className="relative z-10 flex flex-col items-center justify-center text-center px-12">
        {/* Title */}
        <h2 className="text-6xl font-serif font-bold text-yellow-900 mb-10">
          {title}
        </h2>

        {/* Content */}
        <p className="max-w-5xl text-3xl font-serif leading-relaxed">
          {content}
        </p>
      </div>

    </section>
  );
}

/* Main Slide 5 – Twin column parchment with gold divider */
export function MainSlide5({  title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] flex items-center justify-center bg-[#fdf6e3] text-gray-900 overflow-hidden">

      {/* Subtle background icons */}
      <Landmark className="absolute top-20 left-28 w-32 h-32 text-yellow-600 opacity-25 rotate-6" />
      <Scroll className="absolute bottom-24 right-32 w-28 h-28 text-amber-500 opacity-25 rotate-[-8deg]" />
      <BookOpen className="absolute top-1/3 right-1/4 w-28 h-28 text-orange-400 opacity-25" />
      <Feather className="absolute bottom-1/3 left-1/4 w-24 h-24 text-red-400 opacity-25" />
      <Hourglass className="absolute top-1/2 right-16 w-28 h-28 text-emerald-500 opacity-25 rotate-3" />

      {/* Decorative border */}
      <div className="absolute inset-12 border-4 border-amber-600 rounded-lg opacity-30" />
      {/* Gold divider */}
      {/* Content Wrapper */}
      <div className="relative z-10 flex flex-col items-center text-center px-12">
        {/* Title */}
        <h2 className="text-6xl font-serif font-bold text-yellow-900 mb-10">
          {title}
        </h2>

        {/* Content */}
        <p className="max-w-5xl text-3xl font-serif leading-relaxed">
          {content}
        </p>
      </div>
    </section>
  );
}

/* Main Slide 6 – Golden arch motif */
export function MainSlide6({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-yellow-900 via-yellow-800 to-yellow-600 text-yellow-100 flex items-center justify-center overflow-hidden">
      {/* Arch frame */}
      <div className="absolute inset-0 flex items-center justify-center">
        <div className="w-[1200px] h-[800px] border-[16px] border-yellow-400/70 rounded-t-full rounded-b-lg opacity-40"></div>
      </div>

      {/* Inner glow arch */}
      <div className="absolute inset-0 flex items-center justify-center">
        <div className="w-[1000px] h-[650px] border-[10px] border-yellow-300/50 rounded-t-full rounded-b-lg opacity-50"></div>
      </div>

      {/* Content inside the arch */}
      <div className="relative z-10 text-center max-w-5xl">
        <h2 className="text-6xl font-serif font-bold mb-8">{title}</h2>
        <p className="text-3xl font-serif leading-relaxed">{content}</p>
      </div>
    </section>
  );
}



/* Image Slide – Gold pedestal frame */
export function ImageSlide({ title, content, imageUrl, autoGeneratedImage }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-b from-yellow-100 to-yellow-50 flex items-center justify-between px-16">
      {/* Frame */}
      <div className="absolute inset-10 border-[10px] border-yellow-700 rounded-xl"></div>
      
      {/* Left side: Auto-generated image placeholder for 1st term */}
      <div className="relative z-10 w-1/2 h-full flex items-center justify-center pr-12">
        {autoGeneratedImage ? (
          <img 
            src={autoGeneratedImage} 
            alt={title} 
            className="max-w-full max-h-full object-contain rounded-lg shadow-2xl border-8 border-yellow-600" 
          />
        ) : (
          <div className="w-4/5 h-4/5 bg-gradient-to-br from-yellow-50 to-yellow-100 border-8 border-yellow-700 rounded-xl flex flex-col items-center justify-center shadow-2xl">
            <div className="text-yellow-800 text-3xl font-serif font-bold mb-4">🎨 Auto Image Placeholder</div>
            <span className="text-yellow-700 text-xl text-center px-4 font-serif">1st Term: {title}</span>
          </div>
        )}
      </div>
      
      {/* Right side: Term and definition */}
      <div className="relative z-10 w-1/2 pl-12">
        {title && (
          <h3 className="text-6xl font-serif font-bold text-yellow-900 mb-6">{title}</h3>
        )}
        <div className="h-[4px] w-40 bg-gradient-to-r from-yellow-600 to-yellow-800 mb-6"></div>
        {content && (
          <div className="bg-gradient-to-br from-yellow-50/90 to-yellow-100/90 border-l-8 border-yellow-700 p-6 rounded-r-xl shadow-xl backdrop-blur-sm">
            <p className="text-4xl leading-relaxed text-yellow-900 font-serif">{content}</p>
          </div>
        )}
      </div>
    </section>
  );
}

/* End Slide – Strong regal close with diagonal overlay */
export function EndSlide({ message }) {
  return (
    <section className="relative w-[1920px] h-[1080px] flex items-center justify-center text-yellow-100 overflow-hidden">
      {/* Gold gradient */}
      <div className="absolute inset-0 bg-gradient-to-r from-yellow-900 via-yellow-800 to-yellow-600"></div>
      {/* Diagonal overlay */}
      <div className="absolute inset-0 bg-gradient-to-tr from-yellow-700/50 to-yellow-500/30 transform skew-y-3"></div>

      {/* Subtle background icons */}
      <Landmark className="absolute top-24 left-24 w-32 h-32 text-yellow-600 opacity-25" />
      <Scroll className="absolute bottom-28 right-28 w-28 h-28 text-amber-500 opacity-25" />
      <BookOpen className="absolute top-1/3 left-1/4 w-28 h-28 text-orange-400 opacity-25" />
      <Feather className="absolute bottom-1/3 right-1/4 w-24 h-24 text-red-400 opacity-25" />
      <Hourglass className="absolute top-1/2 right-16 w-28 h-28 text-emerald-500 opacity-25" />

      <div className="relative z-10 text-center">
        <h2 className="text-6xl font-serif font-bold mb-4">{message}</h2>
        <p className="text-8xl italic">Thank You</p>
      </div>
    </section>
  );
}


