import React from "react";
import { BookOpen, Scroll, PenTool, GraduationCap } from "lucide-react";

/* Title Slide – Split with vertical divider */
export function TitleSlide({ title, subtitle }) {
  return (
    <section className="w-[1920px] h-[1080px] bg-gradient-to-br from-gray-100 to-gray-200 flex items-center px-24">
      <div className="flex-1 pr-12">
        <h1 className="text-6xl font-serif font-bold text-gray-900 mb-6">{title}</h1>
        <h2 className="text-2xl font-serif italic text-gray-700">{subtitle}</h2>
      </div>
      <div className="w-[3px] h-64 bg-yellow-600"></div>
      <div className="flex-1 pl-12 flex items-center justify-center">
        <div className="w-64 h-64 border-4 border-yellow-600 rounded-full opacity-20"></div>
      </div>
    </section>
  );
}

/* Table of Contents Slide – Scholarly Elegant */
export function TOCSlide({ tocData }) {
  // Handle both old format (items array) and new format (tocData object)
  const title = tocData?.title || "Table of Contents";
  const sections = tocData?.sections || [];
  
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#0e1a2a] text-white flex flex-col items-center justify-center overflow-hidden">
      {/* Elegant border frame */}
      <div className="absolute inset-16 border-4 border-yellow-600/70 rounded-lg"></div>

      {/* Title */}
      <h2 className="text-5xl font-serif font-bold text-yellow-400 mb-20 tracking-wide">
        {title}
      </h2>

      {/* Two-Column Layout for TOC - Simplified to show only main sections */}
      <div className="grid grid-cols-2 gap-20 z-10 max-w-6xl w-full">
        {/* Left Column */}
        <div className="space-y-10">
          {sections.slice(0, Math.ceil(sections.length / 2)).map((section, sectionIndex) => (
            <div key={sectionIndex} className="flex items-center gap-8 text-gray-200 hover:text-yellow-300 transition-colors duration-300 group">
              <div className="w-20 h-20 flex items-center justify-center rounded-full border-3 border-yellow-600 group-hover:border-yellow-500 bg-yellow-600/10 group-hover:bg-yellow-600/20 text-yellow-400 text-2xl font-bold flex-shrink-0 transition-all duration-300 shadow-lg">
                {sectionIndex + 1}
              </div>
              <span className="text-5xl font-bold text-left leading-tight flex-1 group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
            </div>
          ))}
        </div>

        {/* Right Column */}
        <div className="space-y-10">
          {sections.slice(Math.ceil(sections.length / 2)).map((section, sectionIndex) => {
            const actualIndex = Math.ceil(sections.length / 2) + sectionIndex;
            return (
              <div key={actualIndex} className="flex items-center gap-8 text-gray-200 hover:text-yellow-300 transition-colors duration-300 group">
                <div className="w-20 h-20 flex items-center justify-center rounded-full border-3 border-yellow-600 group-hover:border-yellow-500 bg-yellow-600/10 group-hover:bg-yellow-600/20 text-yellow-400 text-2xl font-bold flex-shrink-0 transition-all duration-300 shadow-lg">
                  {actualIndex + 1}
                </div>
                <span className="text-5xl font-bold text-left leading-tight flex-1 group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}


/* Main Slide 1 – Title on top, underline, content below */
export function MainSlide1({ title, content, imageUrl, autoGeneratedImage }) {
  return (
    <section className="w-[1920px] h-[1080px] bg-white text-gray-900 px-24 py-16 flex items-center justify-between">

      <div className="absolute inset-0 opacity-20 bg-[radial-gradient(circle_at_center,rgba(0,0,0,0.05),transparent_70%)]" />

      {/* Scholarly faded icons */}
      <Scroll className="absolute bottom-32 right-24 w-28 h-28 text-[#6e5a3d]/20" />
      <PenTool className="absolute top-1/3 right-1/4 w-24 h-24 text-[#4a3826]/20 rotate-[-15deg]" />
      <GraduationCap className="absolute bottom-20 left-1/4 w-28 h-28 text-[#5c4933]/20" />

      {/* Decorative border frame */}
      <div className="absolute inset-12 border-4 border-[#b9a07f] rounded-2xl opacity-40" />

      {/* Left side: Auto-generated image placeholder for 2nd term */}
      <div className="relative z-10 w-1/2 h-full flex items-center justify-center pr-12">
        {autoGeneratedImage ? (
          <img 
            src={autoGeneratedImage} 
            alt={title} 
            className="max-w-full max-h-full object-contain border-4 border-gray-700 rounded-lg shadow-xl" 
          />
        ) : (
          <div className="w-4/5 h-4/5 bg-white border-4 border-gray-600 rounded-lg flex flex-col items-center justify-center shadow-xl">
            <div className="text-gray-700 text-3xl font-serif font-bold mb-4">🎨 Auto Image Placeholder</div>
            <span className="text-gray-600 text-xl text-center px-4 font-serif">2nd Term: {title}</span>
          </div>
        )}
      </div>

      {/* Right side: Term and definition */}
      <div className="relative z-10 w-1/2 pl-12">
        <h2 className="text-7xl font-serif font-bold mb-4 text-gray-800">{title}</h2>
        <div className="h-[3px] w-40 bg-yellow-600 mb-8"></div>
        {content && (
          <div className="bg-gray-50/80 border-l-4 border-yellow-600 p-6 rounded-r-lg shadow-lg">
            <div className="text-4xl font-serif leading-relaxed text-gray-700">{content}</div>
          </div>
        )}
      </div>
    </section>
  );
}

/* Main Slide 2 – Two columns, left for title+content, right decorative */
export function MainSlide2({ title, content }) {
  return (
    <section className="w-[1920px] h-[1080px] bg-gray-50 text-gray-900 px-20 py-16 flex">

      <div className="absolute inset-0 opacity-20 bg-[radial-gradient(circle_at_center,rgba(0,0,0,0.05),transparent_70%)]" />

      {/* Scholarly faded icons */}
      <Scroll className="absolute bottom-32 right-24 w-28 h-28 text-[#6e5a3d]/20" />
      <PenTool className="absolute top-1/3 right-1/4 w-24 h-24 text-[#4a3826]/20 rotate-[-15deg]" />
      <GraduationCap className="absolute bottom-20 left-1/4 w-28 h-28 text-[#5c4933]/20" />

      {/* Decorative border frame */}
      <div className="absolute inset-12 border-4 border-[#b9a07f] rounded-2xl opacity-40" />

      <div className="flex-1 pr-12">
        <h2 className="text-7xl font-serif font-bold mb-6">{title}</h2>
        <div className="text-4xl font-serif leading-relaxed">{content}</div>
      </div>
      <div className="flex-1 flex items-center justify-center">
        <img src="src/svgs/abroad.svg" alt="abroad" className="w-[700px]"/>
      </div>
    </section>
  );
}

/* Main Slide 3 – Full border frame with content centered */
export function MainSlide3({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-gray-100 to-white text-gray-900 px-24 py-16 flex flex-col items-center justify-center">
      <div className="absolute inset-8 border-4 border-yellow-600 rounded-xl opacity-40"></div>
      <h2 className="text-7xl font-serif font-bold mb-[150px] z-10 mt-[-250px] ">{title}</h2>
      <div className="text-4xl font-serif leading-relaxed max-w-5xl text-center z-10">{content}</div>
    </section>
  );
}

/* Image Slide – Left image, right caption */
export function ImageSlide({ title, content, imageUrl, autoGeneratedImage, caption }) {
  return (
    <section className="w-[1920px] h-[1080px] bg-gray-100 text-gray-900 px-20 py-12 flex items-center">
      {/* Left side: Auto-generated image placeholder for 1st term */}
      <div className="flex-1 flex items-center justify-center pr-12">
        {autoGeneratedImage ? (
          <img 
            src={autoGeneratedImage} 
            alt={title} 
            className="max-w-full max-h-full object-contain border-4 border-gray-700 rounded-lg shadow-xl" 
          />
        ) : (
          <div className="w-4/5 h-4/5 bg-white border-4 border-gray-600 rounded-lg flex flex-col items-center justify-center shadow-xl">
            <div className="text-gray-700 text-3xl font-serif font-bold mb-4">🎨 Auto Image Placeholder</div>
            <span className="text-gray-600 text-xl text-center px-4 font-serif">1st Term: {title}</span>
          </div>
        )}
      </div>
      
      <div className="w-[2px] h-[80%] bg-yellow-600"></div>
      
      {/* Right side: Term and definition */}
      <div className="flex-1 pl-12">
        {title && (
          <h3 className="text-6xl font-serif font-bold mb-6 text-gray-800">{title}</h3>
        )}
        <div className="h-[3px] w-32 bg-yellow-600 mb-6"></div>
        {content && (
          <div className="bg-white/80 border-l-4 border-yellow-600 p-6 rounded-r-lg shadow-lg">
            <p className="text-4xl font-serif leading-relaxed text-gray-700">{content}</p>
          </div>
        )}
      </div>
    </section>
  );
}

/* End Slide – Framed closing */
export function EndSlide({ message }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-gray-200 to-gray-100 flex flex-col items-center justify-center text-gray-900 overflow-hidden">

      <div className="absolute inset-16 border-8 border-[#b9a07f] rounded-xl opacity-50" />

      {/* Scholarly faded icons */}
      <BookOpen className="absolute top-24 left-24 w-28 h-28 text-[#5a4632]/20" />
      <Scroll className="absolute bottom-28 right-24 w-32 h-32 text-[#6e5a3d]/20" />
      <PenTool className="absolute top-1/2 right-1/4 w-24 h-24 text-[#4a3826]/20 rotate-12" />

      <div className="absolute inset-6 border-4 border-yellow-600 rounded-xl"></div>
      <h2 className="text-5xl font-serif font-bold mb-6">{message}</h2>
      <p className="text-8xl font-serif italic text-gray-700">Thank you</p>
    </section>
  );
}

/* Main Slide 4 – Horizontal split (title/content left, content right) */
export function MainSlide4({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-white text-gray-900 flex overflow-hidden">
      {/* Decorative background */}
      <div className="absolute inset-0 bg-gradient-to-br from-gray-100 to-gray-200"></div>
      <div className="absolute top-20 left-20 w-40 h-40 bg-yellow-500/20 rounded-full blur-3xl"></div>

      {/* Left */}
      <div className="flex-1 px-24 py-20 z-10 flex flex-col justify-center">
        <h2 className="text-7xl font-serif font-bold mb-8">{title}</h2>
        <p className="text-4xl font-serif leading-relaxed">{content}</p>
      </div>

      {/* Divider */}
      <div className="w-[3px] bg-yellow-600 opacity-70 my-24"></div>

      {/* Right */}
      <div className="flex-1 px-24 py-20 z-10 flex items-center">
        <img src="src/svgs/studying1.svg" alt="studying1" className="w-[700px]"/>
      </div>
    </section>
  );
}

/* Main Slide 6 – Diagonal/offset orientation */
export function MainSlide6({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gray-100 text-gray-900 flex items-center justify-center overflow-hidden">
      {/* Diagonal accent */}
      <div className="absolute -skew-y-6 top-0 left-0 w-full h-full bg-gradient-to-tr from-yellow-100/40 to-transparent"></div>
      <div className="absolute bottom-10 right-10 w-64 h-64 bg-yellow-500/20 rounded-lg rotate-12 blur-2xl"></div>

      <div className="relative z-10 max-w-4xl text-left">
        <h2 className="text-7xl font-serif font-bold mb-8">{title}</h2>
        <p className="text-4xl font-serif leading-relaxed">{content}</p>
      </div>
    </section>
  );
}


// Keep old component for backward compatibility
export function TOCSlideScholarly({ title = "Table of Contents", items = [] }) {
  const tocData = {
    title,
    sections: items.map(item => ({ title: item, subsections: [] }))
  };
  return <TOCSlide tocData={tocData} />;
}

const ScholarlyElegant = {
  TitleSlide,
  TOCSlide,
  MainSlide1,
  MainSlide2,
  MainSlide3,
  ImageSlide,
  EndSlide,
};

export default ScholarlyElegant;
